### ISSUE TITLE
Bug: clicking action button on non-bootstrap page emits error 

### ISSUE THREAD

**Issue by raswonders** [raswonders/bootstrap-grid-overlay#16]
Error:

popup.js:150 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at addAllBtnListener (popup.js:150:16)
    at addButtonListeners (popup.js:136:5)
    at updateUI (popup.js:15:5)
    at popup.js:11:9

**Comment by raswonders** [comment]
fixed by adding conditional into addAllBtnListener()
